### ISSUE TITLE
Update RewardFacet contract to include ActivityType

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/contracts#109]
### Description
In the subgraph, we want to determine which token are received via an `Action` or `Mission` (ActivityType)

```[tasklist]
### Tasks
- [x] Add bytes32 parameter called activityType to all functions in RewardFacet
- [x] Deploy new RewardFacet to Polygon Mumbai
- [x] Add new RewardFacet ABI to subgraph and JS SDK
```
