### ISSUE TITLE
Gas estimations

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/contracts#111]
## Problem
Developers will want to know how roughly how much gas is used for each contract call. 

## Solution
Use the gas estimation functionality provided by `Foundry` - see **[_Gas Reports_](https://book.getfoundry.sh/forge/gas-reports)**
```[tasklist]
### Tasks
- [ ] Use foundry to generate Gas Reports
- [ ] Calculate an average USD cost for each function on each contract
- [ ] Create a markdown file with a table of average costs for each function on each contract
```

**Comment by tinypell3ts** [comment]
**Ref:** Calculate an average USD cost for each function on each contract
https://chat.openai.com/share/04802cda-7432-4c75-90cd-b4e10b6fddbd

**Comment by tinypell3ts** [comment]
@refugene I would actually just gas snapshot instead of gas reports for this - https://book.getfoundry.sh/forge/gas-snapshots
