### ISSUE TITLE
ERC721 base contract

### ISSUE THREAD

**Issue by george-e-d-g-e** [open-format/contracts#17]
use ERC721A and match thirdwebs ERC721Base functionality

## TODO's:
- [x] add ERC721A
- [x] add solidstate ownable
- [x] ~~add solidstate metadata~~
- [x] ~~add solidstate royalty(ERC2981)~~
- [x] add thirdweb inspired [BatchMintMetadata](https://github.com/thirdweb-dev/contracts/blob/main/contracts/extension/BatchMintMetadata.sol)
- [x] add thirdweb inspired [OperatorFilterer](https://github.com/thirdweb-dev/contracts/blob/main/contracts/extension/OperatorFilterer.sol)
- [x] add thirdweb inspired [Royalty](https://github.com/thirdweb-dev/contracts/blob/main/contracts/extension/Royalty.sol)
- [x] add solidstate multicall
- [x] write tests
- [x] documentation comments
